fixtures:
  repositories:
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    augeasproviders_sysctl:
      repo: "https://github.com/hercules-team/augeasproviders_sysctl.git"
    augeasproviders_core:
      repo: "https://github.com/hercules-team/augeasproviders_core.git"
    mount_core:
      repo: "https://github.com/puppetlabs/puppetlabs-mount_core.git"
